### PR TITLE
DIG-1663: Allow program curators to ingest/delete

### PR DESCRIPTION
**Pull request by SonQBChau**
## What's New

- Curator can now perform ingest and delete actions.
- Reworked authorization to use three separate functions for each action: get, post, delete.
- Updated tests for permissions.
- Changed delete URL from `/authorized/program` to `/ingest/program`.

### How to Test

1. Pull this branch.
2. Pull https://github.com/CanDIG/candigv2-ingest/pull/104.
3. Rebuild, add the curator role, and test ingest or delete actions.

### CODE REVIEW

**Review by mshadbolt — APPROVED** [review]
Made the following checks for functionality:
### Site admin role
* can ingest any program
* is not authorized to read programs if program auth not present
* can read programs if program authorization exists (specific email doesn't need to be specified)
* can delete any program
* can add program authorization

### program curator role
* cannot ingest a program they have not been listed as program curator on
* can ingest a program they have been listed as program curator on
* if json contains multiple programs, only the authorized one will be ingested, error messages are shown for the one that is not ingested
* can read programs they are listed as program curator on
* can delete programs they are listed as program curator on
* Cannot add team members to a program they are listed as curator (not sure if this is expected but it is an opa/auth thing, not katsu)

I also adjusted integration tests in: https://github.com/CanDIG/CanDIGv2/pull/666

**Review by kcranston — CHANGES_REQUESTED** [review]
Small readability comment: in core.py, pretty much every instance of "authenticate" should instead be "authorize". Katsu isn't checking OPA to see if the user is authenticated, but if the user is authorized to do the action. 

Other than that, LGTM.

**Comment by SonQBChau** [comment]
> Small readability comment: in core.py, pretty much every instance of "authenticate" should instead be "authorize". Katsu isn't checking OPA to see if the user is authenticated, but if the user is authorized to do the action.
> 
> Other than that, LGTM.

This is a bit of a hack on my part. I hijacked the built-in authenticate function in Django and overwrote it to use our custom OPA logic. The reason is that it provides a nice workflow (pre-checking requests before processing them, integrating well with Swagger UI, better error handling, etc.).  I would need to write a lot more code otherwise, and simply changing the function name would break it.

**Comment by kcranston** [comment]
Ah, that makes sense.  Do you want to just leave a code comment that explains that where you define the `NetworkAuth` class? Then I am 👍🏼 to merging.

**Comment by SonQBChau** [comment]
comment added

**Review by kcranston — APPROVED** [review]

**Pull request merged**
