### PR TITLE
DIG-1239: Donor explorer api

### PR DESCRIPTION
**Pull request by SonQBChau**
## What's new:
- Implemented DonorExplorerSchema, a new API that requires query service token.
- Allows filtering by primary site, treatment type, chemotherapy drug name, immunotherapy drug name, hormone therapy drug name, and cohorts.
- Returns a list of donor objects including program ID, submitter donor ID, submitter sample IDs, primary site, treatment type, and age at diagnosis.

### How to test:
- Local Testing:
  - Run tox.
  - Ingest a small dataset.
  - Access the Swagger UI and use the token `query` to test the API.
  - Expected outcome: Verify that the API returns a list of donor objects according to the specified filtering criteria.

- Docker Testing:
  - Pull this branch.
  - Execute the `test-integration`.
  - Expected outcome: Ensure that the integration tests pass successfully.

### CODE REVIEW

**Comment by mshadbolt** [comment]
I was able to pull this version and all katsu integration tests pass, getting intermittent errors with htsget only.

**Review by daisieh — APPROVED** [review]
This all looks good, but how is it tested with `make test-integration`? Which test in there tests this?

**Comment by SonQBChau** [comment]
> This all looks good, but how is it tested with `make test-integration`? Which test in there tests this?

No katsu tests in test integration for now (there is a ticket for it). It's just to make sure the stack continue to work

**Comment by daisieh** [comment]
Then it works as expected. ✅

**Review by yavyx — APPROVED** [review]
Tested locally and the filters work as expected, two questions:
- I still had to delete the database to ingest data, is this normal?
- Should the filter strings be limited to the permissible values for that field? Right now it returns an empty string, but an exception might be more useful.

**Comment by SonQBChau** [comment]
- You need to clean the database due to ID collisions
- This API is for internal use, so the query should have the correct values from the front end. If none match, it returns an empty list, which is technically correct. The query service can catch it and display it as an error if desired, but merging two lists in the federation might be easier than dealing with a list and an error.

**Pull request merged**
