### PR TITLE
Sonchau/moh part 13

### PR DESCRIPTION
**Pull request by SonQBChau**
- implement discovery api
- split api to moh and discovery
- update local authorized datasets

### CODE REVIEW

**Review by daisieh — APPROVED** [review]
LGTM

**Comment by kcranston** [comment]
Is there any documentation for the changes to the API? 

Is the count response separated by dataset, or all combined?

**Comment by SonQBChau** [comment]
No, I don't have it yet. Where should I put it?
The count is all combined for now.

**Comment by kcranston** [comment]
https://metadata-service.readthedocs.io/en/develop/ ?

**Pull request merged**
