### PR TITLE
DIG-1460: hotfixes from dev?

### PR DESCRIPTION
**Pull request by daisieh**
I found these changes on the dev server and they seem useful in general?

### CODE REVIEW

**Comment by daisieh** [comment]
Should this EXTERNAL_URL value be set in the container's docker-compose?

**Comment by OrdiNeu** [comment]
> Should this EXTERNAL_URL value be set in the container's docker-compose?

Yes, it needs to be added there as well.

**Comment by SonQBChau** [comment]
Please remove EXTERNAL_URL from the local setting since local does not use env.
Is this related to https://candig.atlassian.net/browse/DIG-1460 ?

**Comment by OrdiNeu** [comment]
> Please remove EXTERNAL_URL from the local setting since local does not use env. Is this related to https://candig.atlassian.net/browse/DIG-1460 ?

We could switch it from `os.environ.get()` to `os.getenv()` with a default value for local builds -- would that be an acceptable compromise?

**Comment by daisieh** [comment]
@OrdiNeu @SonQBChau are we happy with this PR now?

**Comment by SonQBChau** [comment]
looks fine to me

**Pull request merged**
