### PR TITLE
construct url for schema.yml

### PR DESCRIPTION
**Pull request by daisieh**
It is more useful and straightforward to shove the sha into the raw file url and present something like 

```
https://raw.githubusercontent.com/CanDIG/katsu/f144305f03ba09f238d5551c31accb2166518062/chord_metadata_service/mohpackets/docs/schema.yml
```
in the schema description.

### CODE REVIEW

**Comment by SonQBChau** [comment]
I found this actually useful but can we change:
```
Based on https://raw.githubusercontent.com/CanDIG/katsu/1fb740334112a9eef08c1e5a9cd01caf83c75681/chord_metadata_service/mohpackets/docs/schema.yml
```
to 
```
  title: MoH Service API
  version: 1.0.0
  description: This is the RESTful API for the MoH Service.
  URL: https://raw.githubusercontent.com/CanDIG/katsu/1fb740334112a9eef08c1e5a9cd01caf83c75681/chord_metadata_service/mohpackets/docs/schema.yml
  ```
  
So I can extract the link from the schema and return it together with service-info and make it easier to check, something like:
  ```
  {
  "name": "katsu",
  "description": "A CanDIG clinical service"
  "version": "2.3.0",
  "schema_url": "https://raw.githubusercontent.com/CanDIG/katsu/1fb740334112a9eef08c1e5a9cd01caf83c75681/chord_metadata_service/mohpackets/docs/schema.yml",

}
```

**Comment by daisieh** [comment]
The problem is that there isn't a place in OpenAPI spec for a URL of this sort in the info tag. You can still parse this out by looking for the description property and regexing the part you want.

**Comment by SonQBChau** [comment]
You are right. I just think we can shove it in without thinking about following openapi spec. How about we put it in contact? Is it weird?
```
{
  "title": "Sample Pet Store App",
  "summary": "A pet store manager.",
  "description": "This is a sample server for a pet store.",
  "termsOfService": "https://example.com/terms/",
  "contact": {
    "name": "API Support",
    "url": "https://www.example.com/support",
    "email": "support@example.com"
  },
  "license": {
    "name": "Apache 2.0",
    "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
  },
  "version": "1.0.1"
}
```

**Comment by daisieh** [comment]
Yes, I think that's weird. I think that the problem here is that the url we're looking at is actually self-referential and doesn't really belong in any field except the description. Why is it difficult for you to just regex it out?

**Comment by SonQBChau** [comment]
Just exploring options since it looks a little ugly to me, but I can parse it 👍

**Review by SonQBChau — APPROVED** [review]

**Pull request merged**
