### PR TITLE
Sonchau/moh part 29

### PR DESCRIPTION
**Pull request by SonQBChau**
What changes:
- fix the bug in the model Donor to allow null value on arrayfield
- change serializer to allow null
- change `convert.py` script, now it will run both synthetic data and fixtures data and ask for dataset size
- add medium dataset schemas, raw data, synthetic fixture and new relationship JSON
- remove codecov

How to test:
- drop the db and create again
- run migrate
- run convert.py for medium set (just to test if convert script running correctly)
- load new data into db

### CODE REVIEW

**Comment by daisieh** [comment]
When I pull this branch and build/compose, `make test-integration` fails with the following:

```
_____________________________________________________ test_setup_katsu _____________________________________________________

    def test_setup_katsu():
        test_loc = "https://raw.githubusercontent.com/CanDIG/katsu/develop/chord_metadata_service/mohpackets/data/small_dataset/synthetic_data/Program.json"
        response = requests.get(test_loc)
        assert response.status_code == 200
    
        site_admin_token = get_token(username=ENV['CANDIG_SITE_ADMIN_USER'], password=ENV['CANDIG_SITE_ADMIN_PASSWORD'])
        headers = {
            'Authorization': f"Bearer {site_admin_token}",
            'Content-Type': 'application/json; charset=utf-8'
        }
        response = requests.post(f"{ENV['CANDIG_URL']}/katsu/moh/v1/ingest/programs", headers=headers, json=response.json())
        print(response.json())
        if response.status_code >= 400:
            errors = response.json()['error during ingest_programs']
            assert "code='unique'" in errors and "program_id" in errors # this means that the error was just that the program IDs already exist
        else:
            assert response.status_code >= 200 and response.status_code < 300
    
        test_loc = "https://raw.githubusercontent.com/CanDIG/katsu/develop/chord_metadata_service/mohpackets/data/small_dataset/synthetic_data/Donor.json"
        response = requests.get(test_loc)
        assert response.status_code == 200
        response = requests.post(f"{ENV['CANDIG_URL']}/katsu/moh/v1/ingest/donors", headers=headers, json=response.json())
        print(response.json())
        if response.status_code >= 400:
            errors = response.json()['error during ingest_donors']
>           assert "code='unique'" in errors and "donor_id" in errors # this means that the error was just that the program IDs already exist
E           assert ("code='unique'" in '[{}, {}, {}, {}, {}, {}, {}, {}, {\'primary_site\': {0: [ErrorDetail(string=\'"Uterus," is not a valid choice. The va...ary site\\\', \\\'Ureter\\\', \\\'Uterus, NOS\\\', \\\'Vagina\\\', \\\'Vulva\\\']]\', code=\'invalid_choice\')]}}, {}]')

etc/tests/test_integration.py:270: AssertionError
--------------------------------------------------- Captured stdout call ---------------------------------------------------
['2 programs were created.']
{'error during ingest_donors': '[{}, {}, {}, {}, {}, {}, {}, {}, {\'primary_site\': {0: [ErrorDetail(string=\'"Uterus," is not a valid choice. The valid choices are: [[\\\'Accessory sinuses\\\', \\\'Adrenal gland\\\', \\\'Anus and anal canal\\\', \\\'Base of tongue\\\', \\\'Bladder\\\', \\\'Bones, joints and articular cartilage of limbs\\\', \\\'Bones, joints and articular cartilage of other and unspecified sites\\\', \\\'Brain\\\', \\\'Breast\\\', \\\'Bronchus and lung\\\', \\\'Cervix uteri\\\', \\\'Colon\\\', \\\'Connective, subcutaneous and other soft tissues\\\', \\\'Corpus uteri\\\', \\\'Esophagus\\\', \\\'Eye and adnexa\\\', \\\'Floor of mouth\\\', \\\'Gallbladder\\\', \\\'Gum\\\', \\\'Heart, mediastinum, and pleura\\\', \\\'Hematopoietic and reticuloendothelial systems\\\', \\\'Hypopharynx\\\', \\\'Kidney\\\', \\\'Larynx\\\', \\\'Lip\\\', \\\'Liver and intrahepatic bile ducts\\\', \\\'Lymph nodes\\\', \\\'Meninges\\\', \\\'Nasal cavity and middle ear\\\', \\\'Nasopharynx\\\', \\\'Oropharynx\\\', \\\'Other and ill-defined digestive organs\\\', \\\'Other and ill-defined sites\\\', \\\'Other and ill-defined sites in lip, oral cavity and pharynx\\\', \\\'Other and ill-defined sites within respiratory system and intrathoracic organs\\\', \\\'Other and unspecified female genital organs\\\', \\\'Other and unspecified major salivary glands\\\', \\\'Other and unspecified male genital organs\\\', \\\'Other and unspecified parts of biliary tract\\\', \\\'Other and unspecified parts of mouth\\\', \\\'Other and unspecified parts of tongue\\\', \\\'Other and unspecified urinary organs\\\', \\\'Other endocrine glands and related structures\\\', \\\'Ovary\\\', \\\'Palate\\\', \\\'Pancreas\\\', \\\'Parotid gland\\\', \\\'Penis\\\', \\\'Peripheral nerves and autonomic nervous system\\\', \\\'Placenta\\\', \\\'Prostate gland\\\', \\\'Pyriform sinus\\\', \\\'Rectosigmoid junction\\\', \\\'Rectum\\\', \\\'Renal pelvis\\\', \\\'Retroperitoneum and peritoneum\\\', \\\'Skin\\\', \\\'Small intestine\\\', \\\'Spinal cord, cranial nerves, and other parts of central nervous system\\\', \\\'Stomach\\\', \\\'Testis\\\', \\\'Thymus\\\', \\\'Thyroid gland\\\', \\\'Tonsil\\\', \\\'Trachea\\\', \\\'Unknown primary site\\\', \\\'Ureter\\\', \\\'Uterus, NOS\\\', \\\'Vagina\\\', \\\'Vulva\\\']]\', code=\'invalid_choice\')]}}, {}]'}
```

I dropped the database using moh_ingest.py option 3 before running the tests and this still happens.

**Comment by SonQBChau** [comment]
You might want to delete the volume `postgres`, the container `chord-metadata` and `metadata-db`. The flush command deletes all the data but it was unable to change the data structure, so the db needs to be recreated. 

Let me know if this solves the problem.

**Comment by daisieh** [comment]
I deleted the containers and the volume, but am still getting the same error. It's specifically saying that for Donor-9, "Uterus" is not a valid option, and that seems to be true: in permissible_values.py, PRIMARY_SITE, "Uterus" is not listed, only "Uterus, NOS".

**Comment by SonQBChau** [comment]
ah, please use the synthetic data in the PR too:
```
https://raw.githubusercontent.com/CanDIG/katsu/sonchau/moh_part_29/chord_metadata_service/mohpackets/data/medium_dataset/synthetic_data/
```
Nebiyou made some mistakes with the synthetic data and I fixed that in the PR

**Review by yavyx — APPROVED** [review]
Tested and working!

**Pull request merged**
