### PR TITLE
Add EXTERNAL_URL to local.py

### PR DESCRIPTION
**Pull request by OrdiNeu**
# Description
This was a missing piece as to why the nightly build was failing.

### CODE REVIEW

**Comment by SonQBChau** [comment]
Can you explain why do the local settings need external URL? I thought the nightly build using dev settings?

**Comment by OrdiNeu** [comment]
> Can you explain why do the local settings need external URL? I thought the nightly build using dev settings?

How do I configure that from the `.env`?

**Comment by SonQBChau** [comment]
it's in katsu docker-compose `DJANGO_SETTINGS_MODULE=config.settings.dev` (sorry I didn't put it in .env, you could if you want). If there is a bug in getting `DJANGO_SETTINGS_MODULE` then I will fix it

**Comment by SonQBChau** [comment]
By default, if `DJANGO_SETTINGS_MODULE ` is not set, it will use local settings, which is _bad_

**Comment by OrdiNeu** [comment]
Closed after some discussion -- it seems like the real issue here would be that candig-dev somehow built `config.settings.local` instead of `config.settings.dev` somehow

**Pull request closed without merging**
