### PR TITLE
Remove bento codes

### PR DESCRIPTION
**Pull request by SonQBChau**
## What's new:
- update psycopg to use binary instead of pure python package. This removed the need of extra library to build on certain system.
- move whitenoise to dev and prod only, make local env easier to install.
- fix debug_toolbar for dev, now it should show up properly.
- update tox to python 3.12 to match prod env.
- remove bento legacy codes.
- update packages to latest version.

### How to test:
- update katsu to sonchau/tech_debt (cd into katsu and git checkout sonchau/tech_debt)
- make build-katsu and make compose-katsu
- make test-integration
- If you want to test locally, follow readme

### CODE REVIEW

**Comment by kcranston** [comment]
Thanks for all of this! Can you rename this PR to indicate that it is the one that removes the bento code? That would make it easier to find in the future. 

Even better would be to split this into two PRs - one for the bento code and one for all of the other stuff.

**Review by daisieh — COMMENTED** [review]
When I run test-integration, test-ingest-permissions fails with this error: 
```
{'errors': ['treatments: 500 There was a problem proxying the request', 'immunotherapies: 400 null value in column "treatment_uuid_id" of relation "mohpackets_immunotherapy" violates not-null constraint\nDETAIL:  Failing row contains (a6ab51d2-a4ac-4805-a344-a9e19c1994e1, DONOR_2, TR_8, PubChem, Other immunomodulatory substances, Pexidartinib, 8836851, ug/m2, 197, 183, 30bb1ce6-964e-44b4-9295-84f6ca70ca54, SYNTHETIC-2, null).'], 'results': ['Of 1 programs, 1 were created', 'Of 4 donors, 4 were created', 'Of 5 primary_diagnoses, 5 were created', 'Of 5 specimens, 5 were created', 'Of 4 sample_registrations, 4 were created', 'Of 6 treatments, 5 were created', 'Of 2 chemotherapies, 2 were created', 'Of 1 hormone_therapies, 1 were created', 'Of 2 immunotherapies, 1 were created', 'Of 1 surgeries, 1 were created', 'Of 4 followups, 4 were created', 'Of 1 comorbidities, 1 were created']} 201
```

**Comment by SonQBChau** [comment]
I think there is some old data left in the database causing issues. e.g `treatment_uuid_id` should not be null. Can you drop the db and try again?

**Comment by daisieh** [comment]
I dropped the db and recreated it. When I re-ran the tests, I got a random 500 error from ingest:
```
{'SYNTHETIC-2': {'errors': [], 'results': ['Of 1 programs, 1 were created', 'Of 4 donors, 4 were created', 'Of 5 primary_diagnoses, 5 were created', 'Of 5 specimens, 5 were created', 'Of 4 sample_registrations, 4 were created', 'Of 6 treatments, 6 were created', 'Of 2 chemotherapies, 2 were created', 'Of 1 hormone_therapies, 1 were created', 'Of 2 immunotherapies, 2 were created', 'Of 1 surgeries, 1 were created', 'Of 4 followups, 4 were created', 'Of 1 comorbidities, 1 were created']}, 'TEST_2': {'errors': ['specimens: 500 There was a problem proxying the request']}}
```
but I couldn't find any corresponding errors in the katsu container logs.

I then re-ran the tests, to see if maybe it was just a random failure, but then I got this error:
```
FAILED etc/tests/test_integration.py::test_katsu_users_data_access - AssertionError: Expected none of ['SYNTHETIC-1', 'SYNTHETIC-2'] to exist, but at least one was found. Attempt to cl...
```
I then manually (via rapidapi) deleted the programs SYNTHETIC-1 and SYNTHETIC-2, which were apparently not present anymore. Then when I re-ran the tests, I got similar errors to before:
```
{'SYNTHETIC-2': {'errors': ['donors: 500 There was a problem proxying the request', 'specimens: 500 There was a problem proxying the request', 'treatments: 400 null value in column "donor_uuid_id" of relation "mohpackets_treatment" violates not-null constraint\nDETAIL:  Failing row contains (099d3f8f-f4a5-49d0-a547-ffb8bfb1f6f9, TR_1, DONOR_1, PD_1, {"Bone marrow transplant"}, Yes, null, 2021-09, 2022-09, Adjuvant, Palliative, 4, 2, RECIST 1.1, Complete response, Treatment completed as prescribed, null, 11ed7054-97eb-4584-bc1b-9811d749578c, SYNTHETIC-2).', 'followups: 400 null value in column "donor_uuid_id" of relation "mohpackets_followup" violates not-null constraint\nDETAIL:  Failing row contains (a100bcca-6175-4d24-bac6-b98984b03deb, FOLLOW_UP_2, DONOR_1, null, TR_1, 2022-08, Loco-regional progression, Biochemical progression, 2022-05, {"Imaging (procedure)","Laboratory data interpretation (procedur..., {C05}, Lugano staging system, T1d, N1mi, M1a(0), Stage IVBS, null, null, SYNTHETIC-2, null).', 'followups: 400 null value in column "donor_uuid_id" of relation "mohpackets_followup" violates not-null constraint\nDETAIL:  Failing row contains (d68b8c33-55ae-4065-a698-837c07a72bc6, FOLLOW_UP_1, DONOR_1, PD_1, null, 2022-08, Loco-regional progression, Distant recurrence/metastasis, 2022-01, {"Imaging (procedure)","Laboratory data interpretation (procedur..., {C06}, SEER staging system, T2(m), N2c, M1b(1), Stage IIBES, null, 11ed7054-97eb-4584-bc1b-9811d749578c, SYNTHETIC-2, null).', 'followups: 400 null value in column "donor_uuid_id" of relation "mohpackets_followup" violates not-null constraint\nDETAIL:  Failing row contains (60a79f23-32fb-47c9-b9e7-e48340763afc, FOLLOW_UP_3, DONOR_1, null, null, 2022-08, Loco-regional progression, Distant recurrence/metastasis, 2022-01, {"Imaging (procedure)","Laboratory data interpretation (procedur..., {C06}, SEER staging system, T2(m), N2c, M1b(1), Stage IIBES, null, null, SYNTHETIC-2, null).', 'followups: 400 null value in column "donor_uuid_id" of relation "mohpackets_followup" violates not-null constraint\nDETAIL:  Failing row contains (99871612-e116-417e-a752-1ad65bc3816f, FOLLOW_UP_4, DONOR_1, null, null, 2022-08, Loco-regional progression, Biochemical progression, 2022-05, {"Imaging (procedure)","Laboratory data interpretation (procedur..., {C05}, Lugano staging system, T1d, N1mi, M1a(0), Stage IVBS, null, null, SYNTHETIC-2, null).', 'comorbidities: 400 null value in column "donor_uuid_id" of relation "mohpackets_comorbidity" violates not-null constraint\nDETAIL:  Failing row contains (fe8a504b-f118-45fd-9a84-2b0d45465c79, DONOR_1, Yes, Right, 44, C34.9, Unknown, Ablation, null, SYNTHETIC-2).']}, 'TEST_2': {'errors': [], 'results': ['Of 1 programs, 1 were created', 'Of 1 donors, 1 were created', 'Of 1 primary_diagnoses, 1 were created', 'Of 1 specimens, 1 were created', 'Of 1 treatments, 1 were created']}}
```
So it seems like something is unhappy with the db after I ran the `curl -X "DELETE" "http://candig.docker.internal:5080/katsu/v2/authorized/program/SYNTHETIC-1/"` and `SYNTHETIC-2` calls...?

**Comment by SonQBChau** [comment]
can you copy-paste me the full error log? I want to see which test causing this

**Comment by yavyx** [comment]
I did a fresh install of the stack and had 4 failed tests, they don't seem to be related to katsu:

```
FAILED etc/tests/test_integration.py::test_server_count - assert 0 > 0
FAILED etc/tests/test_integration.py::test_services_count - assert 0 > 0
FAILED etc/tests/test_integration.py::test_federation_call - IndexError: list index out of range
FAILED etc/tests/test_integration.py::test_add_server - IndexError: list index out of range
```

Ran tox in the standalone katsu repo and all tests passed.

**Comment by SonQBChau** [comment]
I couldn't find a way to recreate Daisie's error on my machine, so I still need someone to test it on docker stack. No rush though

**Comment by mshadbolt** [comment]
I followed instructions above, checked out this branch, rebuilt stack, ran integration tests, also tried loading the medium dataset. All worked for me. 

Do you want me to also test locally?

**Comment by mshadbolt** [comment]
I decided to go ahead and try following the README, at step 4 I get the following error:
```
(venv) marionshadbolt@Marions-Air katsu % sudo -u postgres psql
sudo: unknown user postgres
sudo: error initializing audit plugin sudoers_audit
```

```
(venv) marionshadbolt@Marions-Air katsu % postgres
postgres does not know where to find the server configuration file.
You must specify the --config-file or -D invocation option or set the PGDATA environment variable.
```

**Comment by SonQBChau** [comment]
You'll need to install postgres on your local system first. It's one of the prerequisites.

**Review by mshadbolt — APPROVED** [review]
All works for me on the stack

**Pull request merged**
