### PR TITLE
Sonchau/drf spectacular

### PR DESCRIPTION
**Pull request by SonQBChau**
This PR includes the upgrade drf_spectacular to replace the old django_swagger. It also fixes the lint style and broken testing for python 3.10

### CODE REVIEW

**Comment by kcranston** [comment]
This looks good to me, but will wait for @daisieh to also have a look.

**Review by kcranston — APPROVED** [review]

**Review by daisieh — COMMENTED** [review]
I get an error "Origin http://docker.localhost:5080 is not allowed by Access-Control-Allow-Origin." Is this something that can be fixed in a Django setting?

**Comment by SonQBChau** [comment]
yea, can you add it in 
```
CORS_ALLOWED_ORIGINS = [
        'http://siteyouwantto.allow.com',
]
```

**Comment by kcranston** [comment]
can you document that note about `CORS_ALLOWED_ORIGINS` somewhere?

**Pull request merged**
