### PR TITLE
Add Data Custodian support to Katsu

### PR DESCRIPTION
**Pull request by justin-ys**
- **WIP: Do not merge**
- Adds boilerplate support for Data Custodians in Katsu
- Ingest endpoints can now be accessed by Custodians (when implemented in OPA) as well as site admins
- Ingest endpoints now use a Mixin for codebase optimization
- Site admins can now access all databases

To be done:
- Data custodians can only write to databases they are authorized to

### CODE REVIEW

**Comment by SonQBChau** [comment]
Based on current progress:
- Assumed that OPA will return the `authorized_datasets_read` and `authorized_datasets_write`, we need to update the code so Data Custodians can read from the `authorized_datasets_write` too. 
- If it turns out OPA will handle all of the roles and authorized_datasets, then we need to rethink how to handle permission and authorization in katsu since it will be unnecessary

**Comment by mshadbolt** [comment]
Is this PR worth keeping around or is the codebase too far past this at this point? 
CC: @daisieh too

**Comment by SonQBChau** [comment]
This is way too old that I don't think it's useful anymore.

**Comment by daisieh** [comment]
Agreed. I'll close this.

**Pull request closed without merging**
